- pygameMenu/menu.py
- pygameMenu/selector.py
Added option to selector objects to provide a default value to display instead of the first in the list. 
Recommended fix to Issue #10 
WARNING: This code is not backwards compatible with code that specifies kwargs for add_selector
> Specify default value for selectors

- README.md
- example.py
- pygameMenu/menu.py
- pygameMenu/textmenu.py
This PR add the support to manage menu using a mouse:
* support is enabled by default (see param ``mouse_enabled``)
* click to select & change selectors
* click on top right corner to go back
Note: some code mutualisations have been performed, and tested using ``example.py`` and ``example2.py`` scripts.
> Add mouse support

- setup.py
Currently, setup.py does not import subpackages which means that running ```python setup.py install``` does not include the ```widgets``` subpackage. 
The fix is just using ```find_packages()``` as shown in [setuptools](https://setuptools.readthedocs.io/en/latest/setuptools.html#using-find-packages).
> Need to import subpackages in setup.py

- pygameMenu/menu.py
- pygameMenu/widgets/menubar.py
Juste a small visual change.
I notice that I need to acmes to the private `_top` attribute outside of the `Menu` class which  not the best. However I'm little bit lost in the used of `_actual` and `_top` attributes. They seem to be used even if are not necessary.
For instance, I'm not sure that the use of `_actual` is necessary here, because the `clear()` method shall be applied on the correct menu:
```
def clear(self):
"""
Full reset menu and clear all widgets.
:return: None
"""
self.full_reset()
del self._actual._option[:]
del self._actual._submenus[:]
```
Should it be ?:
```
def clear(self):
"""
Full reset menu and clear all widgets.
:return: None
"""
self.full_reset()
del self._option[:]
del self._submenus[:]
```
More generally, the `_actual` attribute may be initialized to `None` and …
> MenuBar with a cross for top menu

- pygameMenu/examples/timer_clock.py
Cast to int to avoid the following warning:
```
DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
surface.blit(time_blit, (W_SIZE / 2 - time_blit_size[0] / 2, H_SIZE / 2 - time_blit_size[1] / 2))
```
> Cast to int to avoid DeprecationWarning

- pygameMenu/widgets/textinput.py
If K_ESCAPE was used for back action (i.e. KEY_BACK), and if the cursor was in a `textinput`, the K_ESCAPE did not go in previous menu because the widget was considered updated.
> Fix TextInput K_ESCAPE key update widget only if text is selected

- pygameMenu/examples/simple.py
- pygameMenu/menu.py
I change the `mainloop()` in order to not check the `updated` state otherwise the loop was broken at first event used.
I also add the most simple example of a menu, the idea is to describe this code in the documentation and to keep it as simple as possible to show how it is cool to make a menu with `pygame-menu`.
> Fix mainloop to not break until menu is closed + add example

- setup.py
I noticed that the v2.3.1 have no `.whl` for python2
> Make wheel as universal (compatible py2 and py3)

- docs/_source/themes.rst
- pygame_menu/menu.py
- pygame_menu/scrollarea.py
- pygame_menu/themes.py
- pygame_menu/widgets/core/widget.py
- pygame_menu/widgets/widget/menubar.py
As discussed in #171 this PR introduces `Menu._draw_focus_widget()` method if a widget is active.
> Add widget focus

- pygame_menu/menu.py
- pygame_menu/scrollarea.py
- pygame_menu/widgets/core/selection.py
- pygame_menu/widgets/core/widget.py
- pygame_menu/widgets/selection/highlight.py
Changing the referential of a widget is already implemented in the scroll area it-self.
I  think it should stay managed by the scroll area because it is the container of all the widgets. Thus it is aware about all positions and geometries.
> Remove duplicated methods between widget and scroll area

- pygame_menu/widgets/core/widget.py
Currently showing the following warning:
DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
self._rect = pygame.Rect(0.0, 0.0, 0.0, 0.0)  # type: (pygame.Rect,None)
> Avoid DeprecationWarning by changing floats to ints.

- .travis.yml
- README.rst
- pygame_menu/baseimage.py
- pygame_menu/menu.py
- pygame_menu/scrollarea.py
- pygame_menu/utils.py
- pygame_menu/widgets/core/selection.py
- pygame_menu/widgets/core/widget.py
- pygame_menu/widgets/widget/textinput.py
In a game I'm developing, I explicitly render to a surface which I later scale up to a higher resolution.
This lead me to attempt to fix this in pygame_menu.
Since pygame_menu queries `pygame.display.get_size()` when it needs to use the screen dimensions for positioning etc. it leads to incorrect positioning when rendered to a surface that is of lower size than the main display.
This PR attempts to solve that by allowing the user to pass in a 2-tuple or list of screen dimensions when instantiating a Menu object, which it then stores for further reference.
> Allow the end-user to set the screen-dimensions explicitly rather than querying pygame.display

- pygame_menu/font.py
- pygame_menu/menu.py
- pygame_menu/scrollarea.py
- pygame_menu/themes.py
- requirements.txt
My system (Raspberry PI 3B+ with Raspbian Stretch) doesn't have pygame 1.9.6, and when I tried to build pygame 1.9.6, the result didn't work windowed. So I modified pygamemenu to work with 1.9.3.
One of the changes is something that gets around a problem, perhaps only in 1.9.3 but maybe also in later versions, where if you open enough very large menus, eventually you get a read error on the widget font, perhaps due to some leak in pygame. To get around this, I added a simple font cache.
> pygame 1.9.3 support

- docs/_source/contributors.rst
- pygame_menu/__init__.py
- pygame_menu/widgets/widget/dropselect_multiple.py
- test/test_widgets.py
I encountered what (to me) seem like a bug while working with the dropselect_multiple
Whenever I would pick any option, the onchange callback would return the state of the widget before pressing the button.
To me it seemed it should return the state of the widget after picking an option.
I've copy-pasted code from the dropselect widget, moved some things around and removed a check and now it functions as I expected it to.
You've made some mighty fine code here.
> change now returns new state, not old state

- pygame_menu/_widgetmanager.py
- pygame_menu/widgets/widget/textinput.py
- test/test_widgets.py
I am working on textinput for small screens, while i am using textinput font size 15, the cursor is not following the size.
Hence added an option to declare cursor size.
> Add cursor size for text input

- pygame_menu/_scrollarea.py
- pygame_menu/_widgetmanager.py
- pygame_menu/widgets/core/widget.py
- pygame_menu/widgets/widget/dropselect.py
- pygame_menu/widgets/widget/dropselect_multiple.py
- test/test_widgets.py
- Move ``DropSelect`` scrollbar style to the constructor.
- Make selection drop (``DropSelect``) is called automatically after updating items list, now ``make_selection_drop`` is private and require no ``**kwargs`` argument.
> Dropselect make improve

- pygame_menu/_decorator.py
- pygame_menu/menu.py
- pygame_menu/themes.py
- pygame_menu/utils.py
- pygame_menu/version.py
- pygame_menu/widgets/core/widget.py
- pygame_menu/widgets/widget/button.py
- pygame_menu/widgets/widget/dropselect_multiple.py
- pygame_menu/widgets/widget/label.py
- pygame_menu/widgets/widget/menulink.py
- pygame_menu/widgets/widget/progressbar.py
- pygame_menu/widgets/widget/rangeslider.py
- test/test_themes.py
- test/test_utils.py
- test/test_widget_button.py
Use `callable` instead, which is a Python builtin and accepts also
objects with a `__call__` method.
Fixes #394.
> Remove `is_callable` function.

- pygame_menu/_scrollarea.py
- pygame_menu/locals.py
- pygame_menu/widgets/widget/scrollbar.py
- test/test_menu.py
- test/test_scrollarea.py
- Improve scrollbar hide/show adding new ``force`` param.
> Fix scrollbar hide

- pygame_menu/menu.py
Ignoring KeyError seems to work out...
> Fix adding a frame before all columns are started

- pygame_menu/baseimage.py
- pygame_menu/menu.py
- pygame_menu/version.py
- test/_utils.py
- test/test_widget_none.py
- Fix overflow rounding issues.
> Fix overflow

- pygame_menu/menu.py
Moved the ``self._menubar.set_menu(self)`` after ``self._menubar.set_font()`` to avoid running ``_check_title_color()`` in ``menubar.py`` before a title font color is set.
> Avoid incorrect warning about title font color and menu background color being equal or similar |  #473

- pygame_menu/version.py
- pygame_menu/widgets/widget/button.py
See https://github.com/ppizarror/pygame-menu/issues/482.
This is a very simple change. I've replaced the current `if` statement here to compare against the type `pygame.Menu` directly.
This works in my use case and for `test/test_widget_button.py`, but I have not performed any other testing on this.
> Fix for submenus to be subclasses of pygame.Menu

- docs/_source/contributors.rst
- pygame_menu/widgets/widget/button.py
This is an initial commit which copies some code from the Label widget into Button.
This works in my use cases but could of course use more testing. There's also some code duplicated that might be better put in the Widget base class.
If you are interested in accepting this sort of change, I'd be happy to refactor the code to remove the duplication, or anything else you'd suggest.
___
Example from the project I'm using this in...
In Code:
In game, here is the button in it's default state.
When an item is selected, sometimes the text is too wide for the button, so this allows the text to flow to the next line:
Happy holidays!
> Add wordwrap feature in Button Widget - Fixes #488

- pygame_menu/sound.py
- test/test_sound.py
PR introduces a new method `set_sound_volume(sound_type, volume)` which lets you change the volume of individual sound types after they've been loaded and to reduce code duplication, I've introduced a `play_sound_type(sound_type)` method (if it's fine, could you add it to the pygame-ce version too?).
> set_sound_volume (Sound)

- pygame_menu/widgets/widget/scrollbar.py
- test/test_widget_scrollbar.py
PR refactors the `ScrollBar` widget.
- introduced `_update_slider_position_flags()` to manage the `_at_bottom` and `_at_top` flags, ensuring they reflect the slider's position
- created `_update_slider_rect()` to centralize the logic for updating the slider's rectangle, reducing code duplication
- created `_set_slider_position()` to set the slider's position, update the rectangle, update the flags, and render, making it easier to manage slider changes
- added `is_at_bottom()` and `is_at_top()` to provide ways to check the slider's position
- implemented `bump_to_top()` and `bump_to_bottom()` for easy movement to the slider's extreme positions
- extracted mouse event handling into `_handle_mouse_event()` and touch event handling into `_handle_touch_event()`, making the `update()` method …
> ScrollBar (at_bottom, at_top)

- pygame_menu/widgets/widget/rangeslider.py
- test/test_widget_rangeslider.py
PR introduces a new `set_default_value` method to the `RangeSlider(Widget)` class, which should fix bug #498 by @Retr0-Wolf. I've also added a fresh test to make sure everything behaves the way it should.
> Add `set_default_value` to `RangeSlider(Widget)`

- pygame_menu/_scrollarea.py
- test/test_scrollarea.py
PR introduces a new method `get_scrollbar(position)` that makes it much easier, and cleaner, to grab a scrollbar at a specific position. Previously, the only way to access scrollbars was to reach into the private `_scrollbars` list and do something like `_scrollbars[0]`. Not ideal, especially when you don’t want to rely on internal details or remember which index matches which side.
With `get_scrollbar()`, you can now use a simple position string like `"north"` or `"east"` and get exactly what you need. It makes your code more readable and aligns with good encapsulation practices. It also validates the input, so you're less likely to accidentally pass something weird and have it break silently. On top of that, I added a few unit tests to verify the method works correctly across different …
> Add `get_scrollbar(position)` to access scrollbars by position
