MANIFEST.in, setup.py
I have added setup.py and Manifest files to be able to install the package. Please tell me if i should any changes to the code.
Now it's possible to have a requirements.txt file
`git+https://github.com/asierrayk/pygame-menu.git`
And you can install the package in any project by executing.
`pip install -r requirements.txt`
=> Create source distribution

pygameMenu/menu.py, pygameMenu/selector.py
Add update_selector method so it's possible to modify a selector after
it is created
=> Add update_selector method

pygameMenu/locals.py, pygameMenu/menu.py
I think this should be enough. For the moment I've tested it with just one gamepad I have on hand but will try few more in the coming days.
I am just confused with the Y axis motion. As far as I can tell _logically_ it should be the other way around for up and down. But testing shows it is as I've written here. You may take a look at this.
=> Add gamepad (joystick) support for controlling the menu

pygameMenu/menu.py
when using cx freeze to build my program the pygameMenu show me error like that
=> fix problem NameError: name 'exit' is not defined

README.md, example.py, pygameMenu/fonts.py
Just seen some typos while reading the README, I thought I could correct them for you.
=> Correct some typos

example.py, pygameMenu/menu.py
This changes permit to define class methods as callback for the menu (currently only simple Python functions are accepted).
=> Class method can be set as callback

pygameMenu/menu.py, pygameMenu/textmenu.py
Add arrow in back-box.
Also I performed some renaming: ``rect`` instead of ``anchor`` to be consistent with Pygame naming.
=> Add arrow in back-box in top-right corner

example1.py, example2.py, example3.py, pygameMenu/__init__.py, pygameMenu/events.py, pygameMenu/locals.py, pygameMenu/menu.py, pygameMenu/textmenu.py, pygameMenu/widgets/button.py, pygameMenu/widgets/selector.py, pygameMenu/widgets/textinput.py, pygameMenu/widgets/widget.py
Now cursor can be updated with mouse clicks. Also if widget is not selected the mouse click from Menu event is passed to all widgets (if collided)
=> Added mouse handling to TextInput, new style of constants

README.md, example3.py, pygameMenu/menu.py, pygameMenu/widgets/textinput.py, readme.content.md
The call to ``change()`` was missing.
=> Fix call to callback in text_input

example1.py, example2.py, example3.py, pygameMenu/fonts.py, pygameMenu/menu.py, pygameMenu/widgets/selector.py, pygameMenu/widgets/textinput.py, pygameMenu/widgets/widget.py, setup.py
Added FPS (frames per second) support to menu
=> Add FPS support

README.md, example3.py, pygameMenu/menu.py, pygameMenu/sound.py, pygameMenu/widgets/__init__.py, pygameMenu/widgets/button.py, pygameMenu/widgets/menubar.py, pygameMenu/widgets/selector.py, pygameMenu/widgets/textinput.py, pygameMenu/widgets/widget.py
Now textinput can handle underline
=> Textinput underline

README.md
There was a small mistake as you probably forgot to update the README
=> Updated README to match the code

README.md, pygameMenu/examples/game_selector.py, pygameMenu/examples/multi_input.py, pygameMenu/examples/timer_clock.py, pygameMenu/menu.py, pygameMenu/textmenu.py, test/test_font.py, test/test_menu.py, test/test_sound.py, test/test_version.py, test/test_widgets.py
Proposal for a better naming of the `add_option` (match the name of the widget)
=> Deprecate add_option, now use add_button

pygameMenu/examples/scroll_bar.py, pygameMenu/locals.py, pygameMenu/widgets/__init__.py, pygameMenu/widgets/scrollbar.py, pygameMenu/widgets/widget.py, test/_utils.py, test/test_widgets.py
This is the first step to a scrolling menu: new widget ScrollBar added.
Next step: implement a ScrollArea to manage scrolling in menu.
=> Add a ScrollBar widget

pygameMenu/examples/multi_input.py, pygameMenu/examples/scroll_bar.py, pygameMenu/menu.py, pygameMenu/widgets/scrollbar.py, pygameMenu/widgets/textinput.py
Widget fixed, but now some strange behaviour appears when scrolling from left to right
=> Fixed default value if maxwidth

README.md, pygameMenu/examples/multi_input.py, pygameMenu/menu.py, pygameMenu/version.py, pygameMenu/widgets/__init__.py, pygameMenu/widgets/color_rgb.py, pygameMenu/widgets/textinput.py
=> Added initial color rgb widget

pygameMenu/menu.py
Small changes to complete the last PR
=> Make configure_widget private and add alignment

pygameMenu/menu.py, pygameMenu/textmenu.py
Improve rendering. Text only render once. Improve FPS
=> Improve text rendering

pygameMenu/menu.py, pygameMenu/widgets/label.py
First implementation of the `Label` widget to replace the `TextMenu` class.
See #121
=> First implementation of Label widget

README.rst, docs/_source/add_widgets.rst, docs/_source/create_menu.rst
I think that big part of the documentation is done.
Now it shall be completed during development.
=> Update menu doc with descriptions of some specific options

pygameMenu/baseimage.py, pygameMenu/examples/game_selector.py, pygameMenu/examples/multi_input.py, pygameMenu/examples/scroll_menu.py, pygameMenu/examples/simple.py, pygameMenu/examples/timer_clock.py, pygameMenu/font.py, pygameMenu/menu.py, pygameMenu/themes.py, pygameMenu/widgets/core/selection.py, pygameMenu/widgets/core/widget.py
Now, all the base geometric properties of the menu are provided by Theme. This concludes #162 
This PR also converts all lists to tuples in Theme class as lists are mutable
=> Added widget offset, margin and title to themes

docs/_source/advanced.rst, docs/_source/themes.rst, pygameMenu/widgets/__init__.py, pygameMenu/widgets/core/selection.py, pygameMenu/widgets/core/widget.py, pygameMenu/widgets/selection/highlight.py, pygameMenu/widgets/selection/none.py, pygameMenu/widgets/selection/right_arrow.py
continuation of left arrow selection discussed in #162
=> Improved left arrow, added right arrow, fix docs

README.rst, docs/_source/advanced.rst, docs/_source/baseimage.rst, docs/_source/migration_guide.rst, docs/conf.py, docs/index.rst, pygame_menu/menu.py, pygame_menu/scrollarea.py, pygame_menu/themes.py, setup.py, test/_utils.py, test/test_examples.py, test/test_font.py, test/test_menu.py, test/test_sound.py, test/test_widgets.py
As discussed in #172 added Menu.get_current() method.
=> New menu.get_current() method, added migration guide to docs

.gitignore, pygame_menu/menu.py, pygame_menu/themes.py, pygame_menu/widgets/__init__.py, pygame_menu/widgets/core/__init__.py, pygame_menu/widgets/core/selection.py, pygame_menu/widgets/examples/scrollbar_area.py, pygame_menu/widgets/selection/__init__.py, pygame_menu/widgets/selection/arrow_selection.py, pygame_menu/widgets/selection/highlight.py, pygame_menu/widgets/selection/left_arrow.py, pygame_menu/widgets/selection/none.py, pygame_menu/widgets/selection/right_arrow.py, pygame_menu/widgets/widget/__init__.py, pygame_menu/widgets/widget/button.py, pygame_menu/widgets/widget/image.py, pygame_menu/widgets/widget/label.py, pygame_menu/widgets/widget/menubar.py, pygame_menu/widgets/widget/scrollbar.py, pygame_menu/widgets/widget/selector.py, pygame_menu/widgets/widget/textinput.py, pygame_menu/widgets/widget/vmargin.py
Extract parent class ArrowSelection for LeftArrowSelection and RightArrowSelection.
=> Add blink functionality, and extract parent class ArrowSelection for LeftArrowSelection and RightArrowSelection.

pygame_menu/controls.py, pygame_menu/events.py, pygame_menu/examples/scroll_menu.py, pygame_menu/menu.py, pygame_menu/widgets/core/widget.py, pygame_menu/widgets/widget/colorinput.py, pygame_menu/widgets/widget/textinput.py, test/_utils.py, test/test_widgets.py
Implemented active state (#171) and mousemotion selection
@notruns, @anxuae, @eforgacs 
Suggestions on code or functionality?
This should be the last feature to publish v3
=> Mousemotion feature

docs/_source/create_menu.rst, docs/index.rst, pygame_menu/examples/scroll_menu.py, pygame_menu/examples/simple.py, pygame_menu/examples/timer_clock.py, pygame_menu/menu.py, pygame_menu/widgets/core/widget.py, test/test_menu.py
The `_last_selected_surface ` was never used
Use the tuple comparison to simplify the code
=> Remove unsued variable, clean code

docs/index.rst
The code provided in the First steps example was not runnable. This PR uses separate commits to fix the call to `pygame_menu.Menu` and add import and pass statements.
These can be squashed before merging to maintain a clean commit history.
=> Fix docs first steps code

docs/_source/themes.rst, pygame_menu/themes.py, pygame_menu/widgets/widget/selector.py, pygame_menu/widgets/widget/textinput.py
A selector may have no parameter to pass to the callbacks
=> Relax assert on selector items

pygame_menu/baseimage.py, pygame_menu/font.py, pygame_menu/menu.py, pygame_menu/sound.py, pygame_menu/themes.py, pygame_menu/utils.py, pygame_menu/version.py, pygame_menu/widgets/core/widget.py, pygame_menu/widgets/examples/scrollbar.py, pygame_menu/widgets/widget/colorinput.py, pygame_menu/widgets/widget/label.py, pygame_menu/widgets/widget/menubar.py, pygame_menu/widgets/widget/scrollbar.py, pygame_menu/widgets/widget/textinput.py
=> Widget custom events, fix textinput, pygame v2 compatibility

requirements.txt
The code below is incompatible with `pygame 1.9.4`
https://github.com/ppizarror/pygame-menu/blob/dfb7fe16878b21b44b3da4d85d82eefeb0fbc30f/pygame_menu/themes.py#L196-L198
The required pygame version in `requirements.txt` should now `1.9.6`
=> Upgrade pygame version required

pygame_menu/menu.py, pygame_menu/scrollarea.py, pygame_menu/widgets/core/widget.py, pygame_menu/widgets/widget/button.py, pygame_menu/widgets/widget/menubar.py, pygame_menu/widgets/widget/selector.py, pygame_menu/widgets/widget/textinput.py
Hello everyone,
As discussed in #222, `pygame` now handles the touchscreen separately from mouse.
Here is a first draft of the integration, I'm not sure of everything and I'll be happy to correct anything if you want.
I've tested it on a raspberry pi with a 7" touchscreen and it works. I have some issues with the back button (doesn't always work but maybe it is because it is quite small on the touchscreen.
=> Touchscreen support with pygame 2.0.0

pygame_menu/menu.py
Fixes: 
https://github.com/ppizarror/pygame-menu/issues/232
https://github.com/ppizarror/pygame-menu/issues/233
=> fix two problems with force_fit_text option

pygame_menu/baseimage.py, pygame_menu/examples/game_selector.py, pygame_menu/menu.py, pygame_menu/scrollarea.py, pygame_menu/sound.py, pygame_menu/widgets/core/selection.py, pygame_menu/widgets/core/widget.py, pygame_menu/widgets/examples/scrollbar_area.py, pygame_menu/widgets/selection/arrow_selection.py, pygame_menu/widgets/selection/highlight.py, pygame_menu/widgets/selection/left_arrow.py, pygame_menu/widgets/selection/none.py, pygame_menu/widgets/selection/right_arrow.py, pygame_menu/widgets/widget/button.py, pygame_menu/widgets/widget/colorinput.py, pygame_menu/widgets/widget/image.py, pygame_menu/widgets/widget/menubar.py, pygame_menu/widgets/widget/scrollbar.py, pygame_menu/widgets/widget/selector.py, pygame_menu/widgets/widget/textinput.py, pygame_menu/widgets/widget/vmargin.py, test/test_menu.py, test/test_widgets.py
- Fixes null font rendering and selection effect #237.
=> Fix fontrender widget

pygame_menu/baseimage.py, pygame_menu/events.py, pygame_menu/examples/other/image_background.py, pygame_menu/menu.py, pygame_menu/themes.py, pygame_menu/utils.py, pygame_menu/version.py, pygame_menu/widgets/core/widget.py, pygame_menu/widgets/examples/scrollbar.py, pygame_menu/widgets/examples/scrollbar_area.py, pygame_menu/widgets/selection/highlight.py, pygame_menu/widgets/widget/button.py, pygame_menu/widgets/widget/menubar.py, pygame_menu/widgets/widget/selector.py, test/_utils.py, test/test_menu.py, test/test_widgets.py
=> Fix background color

docs/_source/migration_guide_3_to_4.rst, pygame_menu/baseimage.py, pygame_menu/menu.py, pygame_menu/widgets/core/widget.py, pygame_menu/widgets/widget/colorinput.py, pygame_menu/widgets/widget/menubar.py, pygame_menu/widgets/widget/none.py, pygame_menu/widgets/widget/scrollbar.py, pygame_menu/widgets/widget/textinput.py, test/test_baseimage.py, test/test_menu.py, test/test_selection.py, test/test_widgets.py
- Fix widget positioning and centering.
- Rename ``Widget`` method ``set_selected`` to ``select``.
- Fix colorinput previsualization color render.
- Improve tests.
- Added ``Path`` support on ``BaseImage``, closes #261.
=> Fix centering

README.rst, pygame_menu/examples/__init__.py, pygame_menu/examples/other/dynamic_widget_update.py, pygame_menu/widgets/widget/textinput.py, test/_utils.py, test/test_baseimage.py, test/test_menu.py, test/test_widgets.py
- Fixed support for ``pygame 1.9.3``.
=> Improve pygame support

.readthedocs.yml, README.rst, docs/conf.py, pygame_menu/__init__.py, pygame_menu/baseimage.py, pygame_menu/examples/other/dynamic_widget_update.py, pygame_menu/menu.py, pygame_menu/scrollarea.py, pygame_menu/version.py, pygame_menu/widgets/core/widget.py, pygame_menu/widgets/selection/arrow_selection.py, pygame_menu/widgets/selection/highlight.py, pygame_menu/widgets/widget/colorinput.py, pygame_menu/widgets/widget/menubar.py, pygame_menu/widgets/widget/scrollbar.py, pygame_menu/widgets/widget/textinput.py, pygame_menu/widgets/widget/vmargin.py, setup.py, test/_utils.py, test/test_menu.py, test/test_widgets.py
- Added reset parameter to Menu ``clear`` method, #276.
- Fixed Menu mainloop background function save.
- Fixed ``TextInput`` cursor position and clock.
- Fixed ``pygame 1.9.3`` support.
=> Fixes before v4

.replit, pygame_menu/menu.py, pygame_menu/version.py, pygame_menu/widgets/core/widget.py, pygame_menu/widgets/widget/button.py, pygame_menu/widgets/widget/menubar.py, pygame_menu/widgets/widget/selector.py, pygame_menu/widgets/widget/textinput.py, test/test_widgets.py
- Fix ``Widget`` translation error.
=> Fix translation error

pygame_menu/menu.py, pygame_menu/scrollarea.py, pygame_menu/version.py, pygame_menu/widgets/widget/menubar.py, pygame_menu/widgets/widget/scrollbar.py, pygame_menu/widgets/widget/textinput.py, test/_utils.py, test/test_menu.py
- Improve rect usage on widgets.
- Overflow Menu constructor parameter now accepts single bool value.
- Fix docs
=> Minor fixes

docs/_source/themes.rst, pygame_menu/__init__.py, pygame_menu/baseimage.py, pygame_menu/examples/game_selector.py, pygame_menu/menu.py, pygame_menu/sound.py, pygame_menu/themes.py, pygame_menu/utils.py, pygame_menu/version.py, pygame_menu/widgets/core/widget.py, pygame_menu/widgets/widget/colorinput.py, pygame_menu/widgets/widget/image.py, pygame_menu/widgets/widget/selector.py, pygame_menu/widgets/widget/textinput.py, test/test_themes.py, test/test_widgets.py
=> Fix ascii py2

docs/_source/themes.rst, pygame_menu/__init__.py, pygame_menu/_widgetmanager.py, pygame_menu/baseimage.py, pygame_menu/menu.py, pygame_menu/themes.py, pygame_menu/widgets/core/widget.py, pygame_menu/widgets/widget/dropselect.py, pygame_menu/widgets/widget/dropselect_multiple.py, pygame_menu/widgets/widget/frame.py, pygame_menu/widgets/widget/selector.py, pygame_menu/widgets/widget/textinput.py, test/test_frame.py, test/test_widgets.py
- Fix #297 mods.
- Fix typos.
- Added frame resize support.
=> Mods ascii typos

pygame_menu/menu.py
=> Bye bye warning

pygame_menu/_widgetmanager.py, pygame_menu/themes.py, pygame_menu/version.py, test/test_themes.py
=> Fix widget selection effect copy color

docs/_source/themes.rst, pygame_menu/widgets/__init__.py, pygame_menu/widgets/core/selection.py, pygame_menu/widgets/core/widget.py, pygame_menu/widgets/selection/__init__.py, pygame_menu/widgets/selection/arrow_selection.py, pygame_menu/widgets/selection/highlight.py, pygame_menu/widgets/selection/left_arrow.py, pygame_menu/widgets/selection/none.py, pygame_menu/widgets/selection/right_arrow.py, pygame_menu/widgets/selection/simple.py, test/test_selection.py, test/test_widgets.py
- New SimpleSelection, #325.
- Improve tests.
=> Selection fontcolor

pygame_menu/_widgetmanager.py, pygame_menu/widgets/widget/selector.py, pygame_menu/widgets/widget/toggleswitch.py, test/test_widgets.py
- Added single touch/click toggleswitch, #326.
=> Add singletouch toggleswitch

pygame_menu/menu.py, test/_utils.py, test/test_menu.py
To fix #331 
Tested on a touchscreen device with pygame 1.9.6
=> Relax assertion on touchscreen option

.gitignore, pygame_menu/utils.py, pygame_menu/widgets/core/widget.py, test/test_base.py, test/test_controls.py, test/test_frame.py, test/test_menu.py
- Added get_cursor utils, fixes #330
=> Added get_cursor

docs/_source/gallery.rst, pygame_menu/examples/game_selector.py, pygame_menu/examples/other/scrollbar.py, pygame_menu/examples/other/ui_solar_system.py, pygame_menu/examples/timer_clock.py, pygame_menu/menu.py, pygame_menu/version.py, test/test_menu.py
- Fixed critical error on mainloop execution, #336.
=> Fix mainloop bug

docs/add_widgets.py, pygame_menu/_decorator.py, pygame_menu/_widgetmanager.py, pygame_menu/baseimage.py, pygame_menu/examples/game_selector.py, pygame_menu/examples/other/scrollbar_area.py, pygame_menu/menu.py, pygame_menu/version.py, pygame_menu/widgets/core/widget.py, pygame_menu/widgets/widget/button.py, pygame_menu/widgets/widget/dropselect.py, pygame_menu/widgets/widget/scrollbar.py, pygame_menu/widgets/widget/selector.py, pygame_menu/widgets/widget/toggleswitch.py, test/_utils.py, test/test_menu.py, test/test_widgets.py
- Fix submenu linking issue.
- Fix ``DeprecationWarning: an integer is required (got type float)`` issue.
- Added ``recursive`` to ``Menu.get_submenus()`` method.
=> Fix submenu linking

codecov.yml, pygame_menu/sound.py, pygame_menu/widgets/widget/dropselect.py, pygame_menu/widgets/widget/dropselect_multiple.py, pygame_menu/widgets/widget/selector.py, test/test_sound.py, test/test_widgets.py
=> Fix update list dropselect

pygame_menu/_widgetmanager.py, pygame_menu/menu.py, pygame_menu/widgets/core/widget.py, pygame_menu/widgets/widget/button.py, pygame_menu/widgets/widget/dropselect.py, pygame_menu/widgets/widget/frame.py, pygame_menu/widgets/widget/selector.py, pygame_menu/widgets/widget/table.py, pygame_menu/widgets/widget/textinput.py, pygame_menu/widgets/widget/toggleswitch.py, test/test_frame.py, test/test_widgets.py
- Fix frame selected widget positioning, #339.
- Improve update frame menu management.
- Table now warns if adding widgets that accept events.
=> Fix frame dropselect draw

pygame_menu/widgets/widget/dropselect.py, test/_utils.py, test/test_widgets.py
=> Fix dropselect touch condition

pygame_menu/version.py, pygame_menu/widgets/widget/rangeslider.py, test/test_widget_rangeslider.py
=> Fix rangeslider assertion

.travis.yml, pygame_menu/_widgetmanager.py, pygame_menu/menu.py, pygame_menu/version.py, pygame_menu/widgets/core/widget.py, pygame_menu/widgets/widget/colorinput.py, pygame_menu/widgets/widget/dropselect.py, pygame_menu/widgets/widget/rangeslider.py, pygame_menu/widgets/widget/selector.py, pygame_menu/widgets/widget/textinput.py, pygame_menu/widgets/widget/toggleswitch.py, setup.py, test/test_controls.py, test/test_widget_button.py
=> Keyboard ignore nonphysical

pygame_menu/menu.py, pygame_menu/version.py, pygame_menu/widgets/core/widget.py, pygame_menu/widgets/widget/scrollbar.py
=> Fix gain event

LICENSE, pygame_menu/__init__.py, pygame_menu/_widgetmanager.py, pygame_menu/version.py, setup.py, test/test_font.py
=> Fix font argument as pygame.Font

pygame_menu/menu.py
=> Fix widget selection sound

pygame_menu/_scrollarea.py, pygame_menu/menu.py, test/test_menu.py
=> Add menu get size with border

pygame_menu/examples/other/maze.py, pygame_menu/menu.py, pygame_menu/widgets/core/widget.py, pygame_menu/widgets/widget/rangeslider.py, pygame_menu/widgets/widget/selector.py, pygame_menu/widgets/widget/toggleswitch.py
=> Add menu ignore nonphysical

docs/_source/advanced_controller.rst, docs/index.rst, pygame_menu/_scrollarea.py, pygame_menu/controls.py, pygame_menu/menu.py, pygame_menu/version.py, pygame_menu/widgets/core/widget.py, pygame_menu/widgets/widget/button.py, pygame_menu/widgets/widget/colorinput.py, pygame_menu/widgets/widget/dropselect.py, pygame_menu/widgets/widget/menubar.py, pygame_menu/widgets/widget/rangeslider.py, pygame_menu/widgets/widget/selector.py, pygame_menu/widgets/widget/textinput.py, pygame_menu/widgets/widget/toggleswitch.py, test/test_controls.py, test/test_scrollarea.py, test/test_widget_button.py
- Added ``update_area_color`` method to scrollarea.
- Added ``set_controller`` to ``Menu`` and ``Widget`` classes.
- New ``Controller`` object, #410.
=> New controller

pygame_menu/menu.py, test/_utils.py, test/test_menu.py, test/test_widget_dropselect.py
=> Fix mouse visible condition

pygame_menu/_base.py, pygame_menu/_decorator.py, pygame_menu/_widgetmanager.py, pygame_menu/menu.py, pygame_menu/sound.py, pygame_menu/version.py, pygame_menu/widgets/core/widget.py, pygame_menu/widgets/widget/button.py, pygame_menu/widgets/widget/frame.py, pygame_menu/widgets/widget/label.py, pygame_menu/widgets/widget/menubar.py, pygame_menu/widgets/widget/table.py, pygame_menu/widgets/widget/textinput.py, pygame_menu/widgets/widget/toggleswitch.py, test/test_widget_toggleswitch.py
- Fixes #420.
- Improves #430.
=> Fix toggleswitch font update

pygame_menu/menu.py, pygame_menu/version.py, test/test_menu.py
=> Menu render disable/enable

pygame_menu/baseimage.py, pygame_menu/examples/other/maze.py, pygame_menu/version.py, pygame_menu/widgets/selection/arrow_selection.py, pygame_menu/widgets/widget/button.py, pygame_menu/widgets/widget/colorinput.py, pygame_menu/widgets/widget/rangeslider.py, pygame_menu/widgets/widget/textinput.py, test/_utils.py, test/test_menu.py, test/test_widget_rangeslider.py, test/test_widget_textinput.py
- Added ``keyrepeat`` for textinput/rangeslider.
- Fix verbose for ``WidgetManager``.
=> Keyrepeat option

pygame_menu/menu.py, pygame_menu/themes.py, test/test_widgets.py
=> Added theme.widget_alignment_ignore_scrollbar_thickness

pygame_menu/widgets/widget/rangeslider.py
changed the "width" and "default" parameters to 
"range_width" and "default_value" so they're similar to Doc names
=> Update rangeslider width and default parameter names

pygame_menu/widgets/widget/rangeslider.py
Reverts ppizarror/pygame-menu#472
=> Revert "Update rangeslider width and default parameter names"
